export const SET_AUTHENTICATED_START = 'SET_AUTHENTICATED_START'
export const SET_AUTHENTICATED_SUCCESS = 'SET_AUTHENTICATED_SUCCESS'
export const SET_AUTHENTICATED_FAIL = 'SET_AUTHENTICATED_FAIL'
export const SET_AUTHENTICATED_FINISH = 'SET_AUTHENTICATED_FINISH'