export const GET_PLATOS_START = 'GET_PLATOS_START'
export const GET_PLATOS_SUCCESS = 'GET_PLATOS_SUCCESS'
export const GET_PLATOS_FAIL = 'GET_PLATOS_FAIL'
export const GET_PLATOS_FINISH = 'GET_PLATOS_FINISH'