export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAIL = 'GET_USERS_FAIL'
export const GET_USERS_FINISH = 'GET_USERS_FINISH'

export const DELETE_USERS_START = 'DELETE_USERS_START'
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS'
export const DELETE_USERS_FAIL = 'DELETE_USERS_FAIL'
export const DELETE_USERS_FINISH = 'DELETE_USERS_FINISH'

export const ADD_USERS_START = 'ADD_USERS_START'
export const ADD_USERS_SUCCESS = 'ADD_USERS_SUCCESS'
export const ADD_USERS_FAIL = 'ADD_USERS_FAIL'
export const ADD_USERS_FINISH = 'ADD_USERS_FINISH'

export const EDIT_USERS_START = 'EDIT_USERS_START'
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS'
export const EDIT_USERS_FAIL = 'EDIT_USERS_FAIL'
export const EDIT_USERS_FINISH = 'EDIT_USERS_FINISH'